application:
  name: halo
  formatted-version: 1.0.0-SNAPSHOT
server:
  port: 2080
  use-forward-headers: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Loveslmy_520
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 5
      max-wait: 2000
      validation-query: select 1 from dual
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
    separator: |
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
logging:
  config: classpath:logback.xml
