http:
  port: 80
server:
  port: 443
  use-forward-headers: true
  ssl:
    key-store: 214948636630345.jks
    key-store-type: JKS
    key-password: 214948636630345
  undertow:
    io-threads: 1
    worker-threads: 5
    buffer-size: 512
    directBuffers: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # H2database 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Loveslmy_520
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 5
      max-wait: 2000
      validation-query: select 1 from dual
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
logging:
  file: ./logs/log.log