application:
  name: halo
  formatted-version: 1.0.0-SNAPSHOT
  init:
    data:
      script: initdata.sql
server:
  port: 2080
  use-forward-headers: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Loveslmy_520
    data: classpath:initdata.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
logging:
  config: classpath:logback.xml
