custom:
  server:
    http:
      port: 8080
server:
  port: 8443
  use-forward-headers: true
  ssl:
    key-store: 214948636630345.jks
    key-store-type: JKS
    key-password: 214948636630345
  undertow:
    io-threads: 1
    worker-threads: 5
    buffer-size: 512
    directBuffers: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    # H2database 配置
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/halo/halo
    username: admin
    password: 123456
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
logging:
  file: ./logs/log.log
